version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: portfolio_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: portfolio_adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8085:8080"

volumes:
  postgres_data:

